export const tldAbi = [
  {
    inputs: [
      { name: '_domainName', type: 'string' },
      { name: '_domainHolder', type: 'address' },
      { name: '_referrer', type: 'address' },
    ],
    name: 'mint',
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'payable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'buyingEnabled',
    outputs: [{ name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'price',
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ name: '_domainName', type: 'string' }],
    name: 'getDomainHolder',
    outputs: [{ name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ name: '_domainName', type: 'string' }],
    name: 'getDomainData',
    outputs: [{ name: '', type: 'string' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { name: '_domainName', type: 'string' },
      { name: '_data', type: 'string' },
    ],
    name: 'editData',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ name: '_domainName', type: 'string' }],
    name: 'editDefaultDomain',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ name: '_tokenId', type: 'uint256' }],
    name: 'tokenURI',
    outputs: [{ name: '', type: 'string' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ name: '', type: 'address' }],
    name: 'defaultNames',
    outputs: [{ name: '', type: 'string' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ name: '', type: 'string' }],
    name: 'domains',
    outputs: [
      { name: 'name', type: 'string' },
      { name: 'tokenId', type: 'uint256' },
      { name: 'holder', type: 'address' },
      { name: 'data', type: 'string' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
] as const
